arch: arm64-graviton2
virt: lxd
os: linux
dist: focal
group: edge
language: python
cache: pip

jobs:
  allow_failures:
     env: USES_PYFRC_20=true
  include:
    - stage: format
      python:
        - "3.9.1" # use pypy here when available
      before_install:
        chmod +x the_script
      install:
        - pip install yapf
      script:
        - yapf -ir .
        - ./the_script
        - git diff --stat HEAD
    - stage: test robot.py
      env: USES_PYFRC_20=true
      os: windows
      language: sh
      python:
        - "3.x"
      before_install:
         - choco install python3 --params "/InstallDir:C:\\Python"
         - export PATH="/c/Python:/c/Python/Scripts:$PATH"
         - python -m pip install --upgrade pip wheel
      install:
        - pip install -r requirements.txt
      script: py ./robots/bartholomew-richard-fitzgerald-smythe/robot.py test
