arch: arm64-graviton2
virt: lxd
os: linux
dist: focal
group: edge
language: python
cache: pip

jobs:
  include:
    - stage: print
      install: skip
      script: echo "asdf"
    - stage: format
      python:
        - "3.9.1" # use pypy here when available
      install:
        - pip install yapf
      script:
        - yapf -ir .
        - git diff --stat HEAD
    - stage: test robot.py
      python:
        - "3.9.1"
      before_install:
        - chmod +x ./robots/bartholomew-richard-fitzgerald-smythe/robot.py  
      install:
        # - sudo apt-get install python-pygame
        - pip install -r <(cat requirements.txt | grep -v "pygame")
      script: python ./robots/bartholomew-richard-fitzgerald-smythe/robot.py test