arch: arm64-graviton2
virt: lxd
os: linux
dist: focal
group: edge
language: python
cache: pip
env: 
  - PYFRC_IS_BAD=true  

jobs:
  include:
    - stage: print
      install: skip
      script: echo "asdf"
    - stage: format
      python:
        - "3.9.1" # use pypy here when available
      install:
        - pip install yapf
      script:
        - yapf -ir .
        - git diff --stat HEAD
    - stage: test robot.py
      os: windows
      language: sh
      allow_failures:
       - if: true
      python:
        - "3.x"
      before_install:
         - choco install python3 --params "/InstallDir:C:\\Python"
         - export PATH="/c/Python:/c/Python/Scripts:$PATH"
         - python -m pip install --upgrade pip wheel
      install:
        - pip install -r   requirements.txt
      script: py ./robots/bartholomew-richard-fitzgerald-smythe/robot.py test