# test
language: python
dist: bionic
cache: pip
python:
  - "3.9.1"
  - "pypy3"
before_install:
  - chmod +x ./robots/bartholomew-richard-fitzgerald-smythe/robot.py
install:
  - pip install pyfrc
  - pip install wpilib
  - pip install marsutils
  - pip install pynetworktables
  - pip install robotpy-ctre
  - pip install robotpy-navx
  - pip install robotpy-rev
  - pip install robotpy-rev-color
  - pip install robotpy-hal-sim
script: python ./robots/bartholomew-richard-fitzgerald-smythe/robot.py test
