arch: arm64-graviton2
virt: lxd
os: linux
dist: focal
group: edge
language: python
cache: pip

jobs:
  include:
    - stage: print
      install: skip
      script: echo "asdf"
    - stage: format
      python:
        - "3.9.1" # use pypy here when available
      install:
        - pip install yapf
      script:
        - yapf -ir .
        - git diff --stat HEAD
    - stage: test robot.py
      os: windows
      language: sh
      python:
        - "3.x"
      before_install:
#        - chmod +x ./robots/bartholomew-richard-fitzgerald-smythe/robot.py  
         - choco install python3 --params "/InstallDir:C:\\Python"
         - python -m pip install --upgrade pip wheel
      install:
        - pip install -r   requirements.txt
#           - pip install -r <(cat requirements.txt | grep -v "pygame")
      script: py ./robots/bartholomew-richard-fitzgerald-smythe/robot.py test