#test
os: linux
dist: bionic
arch: arm64-graviton2
language: python
cache: pip

jobs:
  include:
    - stage: print
      install: skip
      script: echo "asdf"
    - stage: format
      python:
        - "pypy3"
      install:
        - pip install yapf
      script:
        - yapf -ir .
        - git diff --stat HEAD
    - stage: test robot.py
      python:
        - "3.9.1"
      before_install:
        - chmod +x ./robots/bartholomew-richard-fitzgerald-smythe/robot.py  
      install:
        - pip install -r requirements.txt
      script: python ./robots/bartholomew-richard-fitzgerald-smythe/robot.py test